version: 2.1
jobs:
  run_hunter:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: "تجهيز المكتبات والتشغيل"
          command: |
            go mod init hunter || true
            go get github.com/btcsuite/btcd/btcec/v2
            go get github.com/btcsuite/btcd/btcutil/base58
            go get golang.org/x/crypto/ripemd160
            go run main.go
workflows:
  hunter_workflow:
    jobs:
      - run_hunter