name: OSAMAZ_HUNTER_GO_NONSTOP

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
    - cron: '30 * * * *'

jobs:
  hunt:
    name: Node-${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.23] # تم رفع النسخة لـ 1.23 لتتوافق مع المكتبات
        node: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install Dependencies
      run: |
        go mod init hunter
        # تثبيت النسخ المتوافقة
        go get github.com/btcsuite/btcd/btcec/v2
        go get github.com/btcsuite/btcd/chaincfg
        go get github.com/btcsuite/btcutil
        go get github.com/decred/dcrd/dcrec/secp256k1/v4
        go get golang.org/x/crypto/ripemd160
        go mod tidy

    - name: Run The Beast (Go Engine)
      run: |
        timeout 55m go run main.go || true
